-- Expose les 4 colonnes de défiscalisation dans les vues screener cgp / cgp_ref
-- (ajoutées en fin de liste de sélection — CREATE OR REPLACE préserve l'ordre existant,
--  la sécurité DEFINER et les grants/REVOKE anon). Permet le filtre « Défiscalisation »
--  du screener (param tax_scheme).
CREATE OR REPLACE VIEW investissement_funds_cgp AS
 SELECT isin, name, product_type, asset_class_broad, asset_class, category_normalized,
    region_normalized, sector, management_style,
    management_company_normalized AS gestionnaire,
    aum_eur, currency, inception_date, track_record_years, ter, ongoing_charges,
    entry_fee_max, exit_fee_max, performance_fee, retrocession_cgp, holding_period_years,
        CASE WHEN __stale AND NOT (__ext_fresh AND performance_1y >= '-60'::integer::numeric AND performance_1y <= 200::numeric) THEN NULL::numeric ELSE performance_1y END::numeric(8,4) AS performance_1y,
        CASE WHEN __stale AND NOT (__ext_fresh AND performance_3y >= '-90'::integer::numeric AND performance_3y <= 1000::numeric) THEN NULL::numeric ELSE inv_annualize_pt(performance_3y, 3::numeric, product_type) END AS performance_3y,
        CASE WHEN __stale AND NOT (__ext_fresh AND performance_5y >= '-95'::integer::numeric AND performance_5y <= 1000::numeric) THEN NULL::numeric ELSE inv_annualize_pt(performance_5y, 5::numeric, product_type) END AS performance_5y,
        CASE WHEN __stale THEN NULL::numeric ELSE average_performance END::numeric(8,4) AS average_performance,
        CASE WHEN __stale OR __insane_1y THEN NULL::numeric ELSE volatility_1y END::numeric(8,4) AS volatility_1y,
        CASE WHEN __stale OR __insane_3y THEN NULL::numeric ELSE volatility_3y END::numeric(8,4) AS volatility_3y,
        CASE WHEN __stale OR __insane_1y THEN NULL::numeric ELSE sharpe_1y END::numeric(8,4) AS sharpe_1y,
        CASE WHEN __stale OR __insane_3y THEN NULL::numeric ELSE sharpe_3y END::numeric(8,4) AS sharpe_3y,
        CASE WHEN __stale OR __insane_1y THEN NULL::numeric ELSE max_drawdown_1y END::numeric(8,4) AS max_drawdown_1y,
        CASE WHEN __stale OR __insane_3y THEN NULL::numeric ELSE max_drawdown_3y END::numeric(8,4) AS max_drawdown_3y,
    sri AS risk_score, sfdr_article, labels, pea_eligible, pea_pme_eligible, per_eligible,
    av_fr_eligible, av_lux_eligible, cto_eligible, ucits_compliant, is_institutional,
        CASE WHEN is_institutional IS FALSE OR is_institutional IS NULL THEN true ELSE false END AS accessible_retail,
    hedged, morningstar_rating, share_class_group_id, kid_url, kid_parsed_at, data_completeness,
    data_source, field_sources, updated_at, is_primary_share_class, tickers, tickers_search,
    allocation_profile, benchmark_index, benchmark_variant, benchmark_is_category,
        CASE WHEN __stale THEN NULL::numeric ELSE alpha_1y END::numeric(8,4) AS alpha_1y,
        CASE WHEN __stale THEN NULL::numeric ELSE alpha_3y END::numeric(8,4) AS alpha_3y,
        CASE WHEN __stale THEN NULL::numeric ELSE alpha_5y END::numeric(8,4) AS alpha_5y,
    esg_exclusions, sustainable_investment_pct, taxonomy_alignment_pct, pai_considered,
    tax_scheme, tax_reduction_rate, tax_lock_up_years, vintage_year
   FROM ( SELECT f_1.isin, f_1.name, f_1.product_type, f_1.management_company, f_1.category,
            f_1.asset_class, f_1.region_exposure, f_1.currency, f_1.hedged, f_1.inception_date,
            f_1.track_record_years, f_1.pea_eligible, f_1.distributor_france, f_1.risk_level,
            f_1.srri, f_1.aum_eur, f_1.morningstar_rating, f_1.ongoing_charges, f_1.data_source,
            f_1.performance_1y, f_1.performance_3y, f_1.performance_5y, f_1.average_performance,
            f_1.volatility_1y, f_1.volatility_3y, f_1.sharpe_1y, f_1.sharpe_3y, f_1.max_drawdown_1y,
            f_1.max_drawdown_3y, f_1.sfdr_article, f_1.ter, f_1.sri, f_1.kid_url, f_1.kid_hash,
            f_1.kid_parsed_at, f_1.data_completeness, f_1.created_at, f_1.updated_at, f_1.field_sources,
            f_1.av_lux_eligible, f_1.share_class_group_id, f_1.management_company_normalized,
            f_1.asset_class_broad, f_1.sector, f_1.region_normalized, f_1.management_style, f_1.labels,
            f_1.per_eligible, f_1.ucits_compliant, f_1.is_institutional, f_1.min_subscription_eur,
            f_1.category_normalized, f_1.ter_pct, f_1.ongoing_charges_pct, f_1.av_fr_eligible,
            f_1.pea_pme_eligible, f_1.cto_eligible, f_1.entry_fee_max, f_1.exit_fee_max,
            f_1.performance_fee, f_1.retrocession_cgp, f_1.holding_period_years, f_1.is_primary_share_class,
            f_1.benchmark_index, f_1.benchmark_code, f_1.benchmark_variant, f_1.tracking_diff_1y,
            f_1.tracking_diff_3y, f_1.tracking_diff_5y, f_1.tracking_diff_computed_at, f_1.tickers,
            f_1.tickers_search, f_1.allocation_profile, f_1.benchmark_is_category, f_1.benchmark_perf_1y,
            f_1.benchmark_perf_3y, f_1.benchmark_perf_5y, f_1.alpha_1y, f_1.alpha_3y, f_1.alpha_5y,
            f_1.benchmark_computed_at, f_1.taxonomy_alignment_pct, f_1.sustainable_investment_pct,
            f_1.pai_considered, f_1.sustainability_source, f_1.sustainability_computed_at, f_1.esg_exclusions,
            f_1.esg_exclusions_source, f_1.esg_exclusions_updated_at,
            f_1.tax_scheme, f_1.tax_reduction_rate, f_1.tax_lock_up_years, f_1.vintage_year,
            inv_prices_stale(cov.last_price_date, cov.n_points, f_1.product_type) AS __stale,
            cov.last_price_date IS NULL AND f_1.updated_at > (CURRENT_DATE - 150) AS __ext_fresh,
            (f_1.product_type = ANY (ARRAY['opcvm'::text, 'etf'::text])) AND f_1.asset_class_broad IS DISTINCT FROM 'crypto'::text AND COALESCE(f_1.name, ''::text) !~* 'leverage|levier|inverse|\mbear\m|ultra|\m[2-3]x\m|\mx[2-3]\m|daily.*[2-3]|crypto|bitcoin|blockchain|digital asset'::text AND f_1.volatility_1y > 60::numeric AS __insane_1y,
            (f_1.product_type = ANY (ARRAY['opcvm'::text, 'etf'::text])) AND f_1.asset_class_broad IS DISTINCT FROM 'crypto'::text AND COALESCE(f_1.name, ''::text) !~* 'leverage|levier|inverse|\mbear\m|ultra|\m[2-3]x\m|\mx[2-3]\m|daily.*[2-3]|crypto|bitcoin|blockchain|digital asset'::text AND (f_1.volatility_3y > 60::numeric OR f_1.max_drawdown_3y < '-90'::integer::numeric) AS __insane_3y
           FROM investissement_funds f_1
             LEFT JOIN investissement_fund_price_coverage cov ON cov.isin = f_1.isin) f;

CREATE OR REPLACE VIEW investissement_funds_cgp_ref AS
 SELECT isin, name, product_type, asset_class_broad, asset_class, category_normalized,
    region_normalized, sector, management_style, gestionnaire, aum_eur, currency, inception_date,
    track_record_years, ter, ongoing_charges, entry_fee_max, exit_fee_max, performance_fee,
    retrocession_cgp, holding_period_years, performance_1y, performance_3y, performance_5y,
    average_performance, volatility_1y, volatility_3y, sharpe_1y, sharpe_3y, max_drawdown_1y,
    max_drawdown_3y, risk_score, sfdr_article, labels, pea_eligible, pea_pme_eligible, per_eligible,
    av_fr_eligible, av_lux_eligible, cto_eligible, ucits_compliant, is_institutional, accessible_retail,
    hedged, morningstar_rating, share_class_group_id, kid_url, kid_parsed_at, data_completeness,
    data_source, field_sources, updated_at, insurers, contracts, is_primary_share_class, tickers,
    tickers_search, allocation_profile, benchmark_index, benchmark_variant, benchmark_is_category,
    alpha_1y, alpha_3y, alpha_5y, maturity_year, maturity_year IS NOT NULL AS is_target_maturity,
    esg_exclusions, sustainable_investment_pct, taxonomy_alignment_pct, pai_considered,
    tax_scheme, tax_reduction_rate, tax_lock_up_years, vintage_year
   FROM ( SELECT c.isin, c.name, c.product_type, c.asset_class_broad, c.asset_class, c.category_normalized,
            c.region_normalized, c.sector, c.management_style, c.gestionnaire, c.aum_eur, c.currency,
            c.inception_date, c.track_record_years, c.ter, c.ongoing_charges, c.entry_fee_max, c.exit_fee_max,
            c.performance_fee, c.retrocession_cgp, c.holding_period_years,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.performance_1y END::numeric(8,4) AS performance_1y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.performance_3y END AS performance_3y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.performance_5y END AS performance_5y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.average_performance END::numeric(8,4) AS average_performance,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.volatility_1y END::numeric(8,4) AS volatility_1y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.volatility_3y END::numeric(8,4) AS volatility_3y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.sharpe_1y END::numeric(8,4) AS sharpe_1y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.sharpe_3y END::numeric(8,4) AS sharpe_3y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.max_drawdown_1y END::numeric(8,4) AS max_drawdown_1y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.max_drawdown_3y END::numeric(8,4) AS max_drawdown_3y,
            c.risk_score, c.sfdr_article, c.labels, c.pea_eligible, c.pea_pme_eligible, c.per_eligible,
            c.av_fr_eligible, c.av_lux_eligible, c.cto_eligible, c.ucits_compliant, c.is_institutional,
            c.accessible_retail, c.hedged, c.morningstar_rating, c.share_class_group_id, c.kid_url,
            c.kid_parsed_at, c.data_completeness, c.data_source, c.field_sources, c.updated_at,
            m.insurers, m.contracts, c.is_primary_share_class, c.tickers, c.tickers_search,
            c.allocation_profile, c.benchmark_index, c.benchmark_variant, c.benchmark_is_category,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.alpha_1y END::numeric(8,4) AS alpha_1y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.alpha_3y END::numeric(8,4) AS alpha_3y,
                CASE WHEN c.product_type = ANY (ARRAY['fcpr'::text, 'fcpi'::text, 'fip'::text, 'fpci'::text]) THEN NULL::numeric ELSE c.alpha_5y END::numeric(8,4) AS alpha_5y,
                CASE WHEN (c.product_type = ANY (ARRAY['opcvm'::text, 'etf'::text])) AND c.asset_class_broad = 'obligation'::text AND c.name ~* '\y20(2[4-9]|3[0-9]|4[0-5])\y'::text AND c.name ~* 'oblig|bond|cr[ée]dit|rendement|[ée]ch[ée]ance|target|matur|portage|mill[ée]sim|horizon|ibonds|\yterm\y|high yield|perspective|opportunit|\ycap\y|buy.?and.?hold'::text THEN (regexp_match(c.name, '\y(20(?:2[4-9]|3[0-9]|4[0-5]))\y'::text))[1]::smallint ELSE NULL::smallint END AS maturity_year,
            c.esg_exclusions, c.sustainable_investment_pct, c.taxonomy_alignment_pct, c.pai_considered,
            c.tax_scheme, c.tax_reduction_rate, c.tax_lock_up_years, c.vintage_year
           FROM investissement_funds_cgp c
             LEFT JOIN investissement_fund_insurers_mv m ON m.isin = c.isin) r;
