-- 14 profils assureurs manquants (fix /qa) : la carte « L'assureur » manquait sur
-- 59 fiches (assureurs sans ligne dans av_insurer_profiles). UPSERT idempotent,
-- contenu factuel curé (public notoire), lux/fonds_euros laissés NULL. 17/07/2026.

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Le Conservateur','fr','Le Conservateur','Groupe d''assurance mutuel français, spécialiste historique de la tontine et de l''assurance-vie. Positionnement patrimonial de long terme, distribué en direct par son réseau de conseillers.', NULL, ARRAY['Spécialiste reconnu de la tontine','Approche patrimoniale de long terme','Modèle mutualiste sans actionnaires'], ARRAY['Offre de niche autour de la tontine','Distribution concentrée sur son réseau propre'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Sogécap','fr','Société Générale','Compagnie d''assurance-vie du groupe Société Générale, au cœur du pôle Société Générale Assurances. Alimente les contrats distribués par les réseaux bancaires du groupe.', NULL, ARRAY['Adossé au groupe Société Générale','Assureur-vie de premier plan en France','Volumes d''actifs importants'], ARRAY['Distribution surtout via les réseaux bancaires du groupe','Marque peu visible auprès du grand public'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('BPCE Vie','fr','BPCE','Assureur-vie du groupe BPCE, adossé au pôle assurance du groupe (Natixis Assurances). Porte les contrats d''assurance-vie distribués par les Banques Populaires et les Caisses d''Épargne.', NULL, ARRAY['Adossé au groupe BPCE','Distribution via les réseaux Banque Populaire et Caisse d''Épargne','Acteur majeur de l''assurance-vie en France'], ARRAY['Distribution concentrée sur les réseaux bancaires du groupe','Marque assureur peu connue en direct'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Garance','fr','Garance','Mutuelle française d''épargne et de retraite, spécialiste de l''épargne-retraite de long terme. Distribue ses contrats d''assurance-vie et de retraite en direct.', NULL, ARRAY['Modèle mutualiste','Expertise de l''épargne-retraite de long terme','Historiquement liée aux artisans et indépendants'], ARRAY['Taille modeste','Gamme de supports plus restreinte que les grands acteurs'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Monceau Assurances','fr','Monceau Assurances','Groupe d''assurance mutualiste français couvrant l''assurance-vie, la prévoyance et les dommages. Propose ses contrats d''épargne principalement via son propre réseau.', NULL, ARRAY['Modèle mutualiste sans actionnaires','Groupe généraliste couvrant vie et dommages','Gestion indépendante'], ARRAY['Taille modeste face aux grands assureurs','Distribution surtout via son réseau propre'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Prépar Vie','fr','BRED Banque Populaire','Compagnie d''assurance-vie de la BRED Banque Populaire, filiale du groupe BPCE. Porte les contrats d''assurance-vie distribués par le réseau de la BRED.', NULL, ARRAY['Adossé à la BRED Banque Populaire','Rattaché au groupe BPCE','Distribution via un réseau bancaire établi'], ARRAY['Distribution concentrée sur le réseau BRED','Notoriété limitée hors de ce réseau'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Afi Esca','fr','Burrus','Compagnie d''assurance française du groupe Burrus, historiquement spécialisée en prévoyance et assurance emprunteur, avec une activité d''épargne et d''assurance-vie. Distribue notamment via les courtiers et CGP.', NULL, ARRAY['Expertise en prévoyance et assurance emprunteur','Adossé au groupe familial Burrus','Ouverture aux courtiers et CGP'], ARRAY['Assurance-vie non cœur de métier historique','Taille modeste sur le marché de l''épargne'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Abeille Retraite Professionnelle','fr','Abeille Assurances (Aéma Groupe)','Entité dédiée à la retraite professionnelle du groupe Abeille Assurances (ex-Aviva France), rattaché à Aéma Groupe. Porte des engagements de retraite supplémentaire de type PER et fonds de retraite professionnelle.', NULL, ARRAY['Adossé au groupe Abeille Assurances (Aéma Groupe)','Spécialisation retraite professionnelle','Héritage de l''ancien réseau Aviva France'], ARRAY['Périmètre centré sur la retraite professionnelle','Marque récente issue du rebranding Aviva'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Asac Fapes','fr','ASAC-FAPES','Association d''épargnants (ASAC-FAPES), et non un assureur. Elle conçoit et anime des contrats d''assurance-vie et de retraite (Solid''R Vie, PER) dont le risque est porté par l''assureur Spirica, filiale du groupe Crédit Agricole.', NULL, ARRAY['Contrats assurés par Spirica (groupe Crédit Agricole)','Modèle associatif au service des adhérents','Gamme incluant une dimension solidaire'], ARRAY['Association et non assureur porteur du risque','Adhésion à l''association requise','Solidité à apprécier au niveau de l''assureur Spirica'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('CALI Europe','lux','Crédit Agricole','Crédit Agricole Life Insurance Europe, compagnie d''assurance-vie luxembourgeoise du groupe Crédit Agricole. Porte des contrats d''assurance-vie de droit luxembourgeois destinés à une clientèle patrimoniale.', NULL, ARRAY['Adossé au groupe Crédit Agricole','Cadre luxembourgeois (triangle de sécurité, super-privilège)','Accès aux supports patrimoniaux (FID, FAS)'], ARRAY['Accès patrimonial avec ticket d''entrée élevé','Distribution via CGP et banques privées'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Sogelife','lux','Société Générale','Bras luxembourgeois de Société Générale Assurances. Compagnie d''assurance-vie de droit luxembourgeois proposant des contrats patrimoniaux haut de gamme à une clientèle fortunée.', NULL, ARRAY['Adossé au groupe Société Générale','Cadre luxembourgeois (triangle de sécurité, super-privilège)','Expertise patrimoniale (FID, FAS, multi-devises)'], ARRAY['Accès patrimonial avec ticket d''entrée élevé','Distribution ciblée CGP et banque privée'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Swiss Life Luxembourg','lux','Swiss Life','Bras luxembourgeois du groupe Swiss Life. Compagnie d''assurance-vie de droit luxembourgeois spécialisée dans les contrats patrimoniaux et transfrontaliers pour une clientèle internationale.', NULL, ARRAY['Adossé au groupe Swiss Life','Cadre luxembourgeois (triangle de sécurité, super-privilège)','Expertise transfrontalière et multi-devises'], ARRAY['Accès patrimonial avec ticket d''entrée élevé','Distribution ciblée sur les CGP et banques privées'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('Allianz Life Luxembourg','lux','Allianz','Bras luxembourgeois du groupe Allianz. Compagnie d''assurance-vie de droit luxembourgeois proposant des contrats patrimoniaux à une clientèle fortunée et internationale.', NULL, ARRAY['Adossé au groupe Allianz','Cadre luxembourgeois (triangle de sécurité, super-privilège)','Solidité financière d''un grand groupe international'], ARRAY['Accès patrimonial avec ticket d''entrée élevé','Distribution ciblée CGP et banque privée'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();

INSERT INTO public.investissement_av_insurer_profiles (company, kind, groupe, positionnement, fonds_euros, forces, limites, lux, source, updated_at) VALUES
('AFI ESCA Luxembourg','lux','Burrus','Bras luxembourgeois d''AFI ESCA, du groupe Burrus. Compagnie d''assurance-vie de droit luxembourgeois proposant des contrats patrimoniaux distribués via les courtiers et CGP.', NULL, ARRAY['Rattaché au groupe Burrus (AFI ESCA)','Cadre luxembourgeois (triangle de sécurité, super-privilège)','Ouverture aux courtiers et CGP'], ARRAY['Acteur de taille modeste au Luxembourg','Accès patrimonial ciblé, ticket d''entrée élevé'], NULL, 'qa curation 2026-07-17', now())
ON CONFLICT (company) DO UPDATE SET kind=EXCLUDED.kind, groupe=EXCLUDED.groupe, positionnement=EXCLUDED.positionnement, fonds_euros=EXCLUDED.fonds_euros, forces=EXCLUDED.forces, limites=EXCLUDED.limites, source=EXCLUDED.source, updated_at=now();
